# Generated by Django 2.0.3 on 2018-03-10 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountID', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billingID', models.AutoField(primary_key=True, serialize=False)),
                ('autoBillingOn', models.BooleanField(default=False)),
                ('chargeInterval', models.PositiveIntegerField()),
                ('chargeAmount', models.CharField(max_length=7)),
                ('paypalEmailAccount', models.EmailField(max_length=254)),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyadmin.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('lastName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('starchPref', models.CharField(blank=True, max_length=50)),
                ('proteinPref', models.CharField(blank=True, max_length=50)),
                ('flavorPref', models.CharField(blank=True, max_length=50)),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('glutenFree', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyadmin.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empID', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=50)),
                ('pay', models.PositiveIntegerField()),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyadmin.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('mealID', models.AutoField(primary_key=True, serialize=False)),
                ('mealName', models.CharField(max_length=50, unique=True)),
                ('flavor', models.CharField(max_length=50)),
                ('protein', models.CharField(max_length=50)),
                ('starch', models.CharField(max_length=50)),
                ('vegan', models.BooleanField()),
                ('vegetarian', models.BooleanField()),
                ('glutenFree', models.BooleanField()),
                ('empID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyadmin.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Meal_History',
            fields=[
                ('historyItemID', models.AutoField(primary_key=True, serialize=False)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyadmin.Customer')),
                ('mealName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyadmin.Meal', to_field='mealName')),
            ],
        ),
        migrations.CreateModel(
            name='Meal_Review',
            fields=[
                ('mealReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('reviewText', models.CharField(max_length=500)),
                ('mealName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyadmin.Meal', to_field='mealName')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyadmin.Customer', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyadmin.Customer')),
                ('empID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyadmin.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNum', models.CharField(blank=True, max_length=12)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=20)),
                ('zipCode', models.PositiveIntegerField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyadmin.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='meal_history',
            name='mealReviewID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyadmin.Meal_Review'),
        ),
    ]
